DROP TABLE ADJACENCY_MATRIX_LOG CASCADE CONSTRAINTS;

CREATE TABLE ADJACENCY_MATRIX_LOG
(
  ADMAITER  NUMBER,
  ADMAROW   NUMBER,
  ADMACOL   NUMBER,
  ADMAVAL   NUMBER,
  STRATEGY  NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADJACENCY_MATRIX_LOG IS 'Log of adjacency matrices';

COMMENT ON COLUMN ADJACENCY_MATRIX_LOG.ADMAITER IS 'Number of simulation';

COMMENT ON COLUMN ADJACENCY_MATRIX_LOG.ADMAROW IS 'Row of adjacency matrix';

COMMENT ON COLUMN ADJACENCY_MATRIX_LOG.ADMACOL IS 'Column of adjacency matrix';

COMMENT ON COLUMN ADJACENCY_MATRIX_LOG.ADMAVAL IS 'Value of row,column position';

COMMENT ON COLUMN ADJACENCY_MATRIX_LOG.STRATEGY IS 'Type of simulation for the number of simulation';


