DROP TABLE SAMPLE_ECOLI34 CASCADE CONSTRAINTS;

CREATE TABLE SAMPLE_ECOLI34
(
  V1  VARCHAR2(4000 BYTE),
  V2  VARCHAR2(4000 BYTE),
  V3  VARCHAR2(4000 BYTE),
  V4  VARCHAR2(4000 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


