DROP TABLE SAMPLE_ECOLI_CTRL CASCADE CONSTRAINTS;

CREATE TABLE SAMPLE_ECOLI_CTRL
(
  V1  INTEGER,
  V2  INTEGER,
  V3  INTEGER,
  V4  INTEGER,
  V5  INTEGER,
  V6  INTEGER,
  V7  INTEGER,
  V8  INTEGER,
  V9  INTEGER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


