library("RCytoscape")

cy = CytoscapeConnection ()
pluginVersion (cy)

g <- new ('graphNEL', edgemode='directed')
g <- graph::addNode ('lacA', g)
g <- graph::addNode ('lacI', g)
g <- graph::addNode ('lacY', g)
g <- graph::addNode ('lacZ', g)
g <- graph::addNode ('rpoD', g)
g <- graph::addNode ('znuA', g)
g <- graph::addNode ('hns', g)
g <- graph::addNode ('crp', g)
g <- graph::addNode ('ttdA', g)
g <- graph::addNode ('ttdB', g)
g <- graph::addNode ('ttdR', g)
g <- graph::addNode ('ttdT', g)
g <- graph::addNode ('zraP', g)
g <- graph::addNode ('zraR', g)
g <- graph::addNode ('zraS', g)
g <- graph::addNode ('arsB', g)

cw <- new.CytoscapeWindow ('E. coli (strong) - Modules: 34(Lactose), 37(Zinc), 40(Sodium), 52(Phosphorelay), 55(arsenic)', graph=g, overwriteWindow=TRUE)
displayGraph (cw)

layoutNetwork (cw, layout.name='grid')
redraw (cw)

g <- cw@graph
g <- initEdgeAttribute (graph=g, attribute.name='edgeType',attribute.type='char',default.value='regulates to')
g <- initEdgeAttribute (graph=g, attribute.name='weight',attribute.type='numeric',default.value='unspecified')

g <- graph::addEdge ('lacA','lacI', g)
g <- graph::addEdge ('lacA','lacY', g)
g <- graph::addEdge ('lacA','lacZ', g)
g <- graph::addEdge ('lacA','rpoD', g)
g <- graph::addEdge ('lacA','znuA', g)
g <- graph::addEdge ('lacA','hns', g)
g <- graph::addEdge ('lacA','crp', g)
g <- graph::addEdge ('lacA','ttdA', g)
g <- graph::addEdge ('lacA','ttdB', g)
g <- graph::addEdge ('lacA','ttdR', g)
g <- graph::addEdge ('lacA','ttdT', g)
g <- graph::addEdge ('lacA','zraP', g)
g <- graph::addEdge ('lacA','zraR', g)
g <- graph::addEdge ('lacA','zraS', g)
g <- graph::addEdge ('lacA','arsB', g)
g <- graph::addEdge ('lacI','lacA', g)
g <- graph::addEdge ('lacI','lacY', g)
g <- graph::addEdge ('lacI','lacZ', g)
g <- graph::addEdge ('lacI','rpoD', g)
g <- graph::addEdge ('lacI','znuA', g)
g <- graph::addEdge ('lacI','hns', g)
g <- graph::addEdge ('lacI','crp', g)
g <- graph::addEdge ('lacI','ttdA', g)
g <- graph::addEdge ('lacI','ttdB', g)
g <- graph::addEdge ('lacI','ttdR', g)
g <- graph::addEdge ('lacI','ttdT', g)
g <- graph::addEdge ('lacI','zraP', g)
g <- graph::addEdge ('lacI','zraR', g)
g <- graph::addEdge ('lacI','zraS', g)
g <- graph::addEdge ('lacI','arsB', g)
g <- graph::addEdge ('lacY','lacI', g)
g <- graph::addEdge ('lacY','lacZ', g)
g <- graph::addEdge ('lacY','znuA', g)
g <- graph::addEdge ('lacY','crp', g)
g <- graph::addEdge ('lacY','ttdA', g)
g <- graph::addEdge ('lacY','ttdB', g)
g <- graph::addEdge ('lacY','ttdR', g)
g <- graph::addEdge ('lacY','zraP', g)
g <- graph::addEdge ('lacY','zraR', g)
g <- graph::addEdge ('lacY','zraS', g)
g <- graph::addEdge ('lacY','arsB', g)
g <- graph::addEdge ('lacZ','znuA', g)
g <- graph::addEdge ('lacZ','crp', g)
g <- graph::addEdge ('lacZ','ttdB', g)
g <- graph::addEdge ('lacZ','ttdR', g)
g <- graph::addEdge ('lacZ','zraP', g)
g <- graph::addEdge ('lacZ','zraR', g)
g <- graph::addEdge ('lacZ','zraS', g)
g <- graph::addEdge ('rpoD','lacA', g)
g <- graph::addEdge ('rpoD','lacI', g)
g <- graph::addEdge ('rpoD','lacY', g)
g <- graph::addEdge ('rpoD','lacZ', g)
g <- graph::addEdge ('rpoD','znuA', g)
g <- graph::addEdge ('rpoD','hns', g)
g <- graph::addEdge ('rpoD','crp', g)
g <- graph::addEdge ('rpoD','ttdA', g)
g <- graph::addEdge ('rpoD','ttdB', g)
g <- graph::addEdge ('rpoD','ttdR', g)
g <- graph::addEdge ('rpoD','ttdT', g)
g <- graph::addEdge ('rpoD','zraP', g)
g <- graph::addEdge ('rpoD','zraR', g)
g <- graph::addEdge ('rpoD','zraS', g)
g <- graph::addEdge ('rpoD','arsB', g)
g <- graph::addEdge ('znuA','lacY', g)
g <- graph::addEdge ('znuA','lacZ', g)
g <- graph::addEdge ('znuA','crp', g)
g <- graph::addEdge ('znuA','ttdA', g)
g <- graph::addEdge ('znuA','ttdB', g)
g <- graph::addEdge ('znuA','ttdR', g)
g <- graph::addEdge ('znuA','zraP', g)
g <- graph::addEdge ('znuA','zraR', g)
g <- graph::addEdge ('znuA','zraS', g)
g <- graph::addEdge ('hns','lacI', g)
g <- graph::addEdge ('hns','lacY', g)
g <- graph::addEdge ('hns','lacZ', g)
g <- graph::addEdge ('hns','rpoD', g)
g <- graph::addEdge ('hns','znuA', g)
g <- graph::addEdge ('hns','crp', g)
g <- graph::addEdge ('hns','ttdA', g)
g <- graph::addEdge ('hns','ttdB', g)
g <- graph::addEdge ('hns','ttdR', g)
g <- graph::addEdge ('hns','ttdT', g)
g <- graph::addEdge ('hns','zraP', g)
g <- graph::addEdge ('hns','zraR', g)
g <- graph::addEdge ('hns','zraS', g)
g <- graph::addEdge ('hns','arsB', g)
g <- graph::addEdge ('crp','lacI', g)
g <- graph::addEdge ('crp','lacY', g)
g <- graph::addEdge ('crp','lacZ', g)
g <- graph::addEdge ('crp','znuA', g)
g <- graph::addEdge ('crp','ttdA', g)
g <- graph::addEdge ('crp','ttdB', g)
g <- graph::addEdge ('crp','ttdR', g)
g <- graph::addEdge ('crp','ttdT', g)
g <- graph::addEdge ('crp','zraP', g)
g <- graph::addEdge ('crp','zraR', g)
g <- graph::addEdge ('crp','zraS', g)
g <- graph::addEdge ('crp','arsB', g)
g <- graph::addEdge ('ttdA','lacI', g)
g <- graph::addEdge ('ttdA','lacY', g)
g <- graph::addEdge ('ttdA','lacZ', g)
g <- graph::addEdge ('ttdA','znuA', g)
g <- graph::addEdge ('ttdA','crp', g)
g <- graph::addEdge ('ttdA','ttdB', g)
g <- graph::addEdge ('ttdA','ttdR', g)
g <- graph::addEdge ('ttdA','zraP', g)
g <- graph::addEdge ('ttdA','zraR', g)
g <- graph::addEdge ('ttdA','zraS', g)
g <- graph::addEdge ('ttdA','arsB', g)
g <- graph::addEdge ('ttdB','lacY', g)
g <- graph::addEdge ('ttdB','lacZ', g)
g <- graph::addEdge ('ttdB','znuA', g)
g <- graph::addEdge ('ttdB','crp', g)
g <- graph::addEdge ('ttdB','ttdA', g)
g <- graph::addEdge ('ttdB','ttdR', g)
g <- graph::addEdge ('ttdB','zraP', g)
g <- graph::addEdge ('ttdB','zraR', g)
g <- graph::addEdge ('ttdB','zraS', g)
g <- graph::addEdge ('ttdB','arsB', g)
g <- graph::addEdge ('ttdR','lacY', g)
g <- graph::addEdge ('ttdR','lacZ', g)
g <- graph::addEdge ('ttdR','znuA', g)
g <- graph::addEdge ('ttdR','crp', g)
g <- graph::addEdge ('ttdR','ttdA', g)
g <- graph::addEdge ('ttdR','ttdB', g)
g <- graph::addEdge ('ttdR','zraP', g)
g <- graph::addEdge ('ttdR','zraR', g)
g <- graph::addEdge ('ttdR','zraS', g)
g <- graph::addEdge ('ttdT','lacA', g)
g <- graph::addEdge ('ttdT','lacI', g)
g <- graph::addEdge ('ttdT','lacY', g)
g <- graph::addEdge ('ttdT','lacZ', g)
g <- graph::addEdge ('ttdT','rpoD', g)
g <- graph::addEdge ('ttdT','znuA', g)
g <- graph::addEdge ('ttdT','hns', g)
g <- graph::addEdge ('ttdT','crp', g)
g <- graph::addEdge ('ttdT','ttdA', g)
g <- graph::addEdge ('ttdT','ttdB', g)
g <- graph::addEdge ('ttdT','ttdR', g)
g <- graph::addEdge ('ttdT','zraP', g)
g <- graph::addEdge ('ttdT','zraR', g)
g <- graph::addEdge ('ttdT','zraS', g)
g <- graph::addEdge ('ttdT','arsB', g)
g <- graph::addEdge ('zraP','lacY', g)
g <- graph::addEdge ('zraP','lacZ', g)
g <- graph::addEdge ('zraP','znuA', g)
g <- graph::addEdge ('zraP','crp', g)
g <- graph::addEdge ('zraP','ttdA', g)
g <- graph::addEdge ('zraP','ttdB', g)
g <- graph::addEdge ('zraP','ttdR', g)
g <- graph::addEdge ('zraP','zraR', g)
g <- graph::addEdge ('zraP','zraS', g)
g <- graph::addEdge ('zraP','arsB', g)
g <- graph::addEdge ('zraR','lacY', g)
g <- graph::addEdge ('zraR','lacZ', g)
g <- graph::addEdge ('zraR','znuA', g)
g <- graph::addEdge ('zraR','crp', g)
g <- graph::addEdge ('zraR','ttdA', g)
g <- graph::addEdge ('zraR','ttdB', g)
g <- graph::addEdge ('zraR','ttdR', g)
g <- graph::addEdge ('zraR','zraP', g)
g <- graph::addEdge ('zraR','zraS', g)
g <- graph::addEdge ('zraR','arsB', g)
g <- graph::addEdge ('zraS','lacY', g)
g <- graph::addEdge ('zraS','lacZ', g)
g <- graph::addEdge ('zraS','znuA', g)
g <- graph::addEdge ('zraS','crp', g)
g <- graph::addEdge ('zraS','ttdA', g)
g <- graph::addEdge ('zraS','ttdB', g)
g <- graph::addEdge ('zraS','ttdR', g)
g <- graph::addEdge ('zraS','zraP', g)
g <- graph::addEdge ('zraS','zraR', g)
g <- graph::addEdge ('arsB','lacI', g)
g <- graph::addEdge ('arsB','lacY', g)
g <- graph::addEdge ('arsB','lacZ', g)
g <- graph::addEdge ('arsB','rpoD', g)
g <- graph::addEdge ('arsB','znuA', g)
g <- graph::addEdge ('arsB','crp', g)
g <- graph::addEdge ('arsB','ttdA', g)
g <- graph::addEdge ('arsB','ttdB', g)
g <- graph::addEdge ('arsB','ttdR', g)
g <- graph::addEdge ('arsB','ttdT', g)
g <- graph::addEdge ('arsB','zraP', g)
g <- graph::addEdge ('arsB','zraR', g)
g <- graph::addEdge ('arsB','zraS', g)

edgeData (g, 'lacA','lacI','weight') <- 0.79
edgeData (g, 'lacA','lacY','weight') <- 1
edgeData (g, 'lacA','lacZ','weight') <- 0.35
edgeData (g, 'lacA','rpoD','weight') <- 0.97
edgeData (g, 'lacA','znuA','weight') <- 0.26
edgeData (g, 'lacA','hns','weight') <- 1
edgeData (g, 'lacA','crp','weight') <- 0.37
edgeData (g, 'lacA','ttdA','weight') <- 0.63
edgeData (g, 'lacA','ttdB','weight') <- 0.34
edgeData (g, 'lacA','ttdR','weight') <- 0.27
edgeData (g, 'lacA','ttdT','weight') <- 0.57
edgeData (g, 'lacA','zraP','weight') <- 0.1
edgeData (g, 'lacA','zraR','weight') <- 0.58
edgeData (g, 'lacA','zraS','weight') <- 0.22
edgeData (g, 'lacA','arsB','weight') <- 0.59
edgeData (g, 'lacI','lacA','weight') <- 0.06
edgeData (g, 'lacI','lacY','weight') <- 0.61
edgeData (g, 'lacI','lacZ','weight') <- 0.6
edgeData (g, 'lacI','rpoD','weight') <- 0.3
edgeData (g, 'lacI','znuA','weight') <- 0.65
edgeData (g, 'lacI','hns','weight') <- 0.33
edgeData (g, 'lacI','crp','weight') <- 0.74
edgeData (g, 'lacI','ttdA','weight') <- 0.85
edgeData (g, 'lacI','ttdB','weight') <- 0.72
edgeData (g, 'lacI','ttdR','weight') <- 0.57
edgeData (g, 'lacI','ttdT','weight') <- 0.16
edgeData (g, 'lacI','zraP','weight') <- 0.47
edgeData (g, 'lacI','zraR','weight') <- 0.75
edgeData (g, 'lacI','zraS','weight') <- 0.67
edgeData (g, 'lacI','arsB','weight') <- 0.53
edgeData (g, 'lacY','lacI','weight') <- 0.14
edgeData (g, 'lacY','lacZ','weight') <- 0.48
edgeData (g, 'lacY','znuA','weight') <- 0.3
edgeData (g, 'lacY','crp','weight') <- 0.36
edgeData (g, 'lacY','ttdA','weight') <- 0.24
edgeData (g, 'lacY','ttdB','weight') <- 0.17
edgeData (g, 'lacY','ttdR','weight') <- 0.31
edgeData (g, 'lacY','zraP','weight') <- 0.23
edgeData (g, 'lacY','zraR','weight') <- 0.08
edgeData (g, 'lacY','zraS','weight') <- 0.11
edgeData (g, 'lacY','arsB','weight') <- 0.41
edgeData (g, 'lacZ','znuA','weight') <- 0.09
edgeData (g, 'lacZ','crp','weight') <- 0.06
edgeData (g, 'lacZ','ttdB','weight') <- 0.13
edgeData (g, 'lacZ','ttdR','weight') <- 0.09
edgeData (g, 'lacZ','zraP','weight') <- 0.07
edgeData (g, 'lacZ','zraR','weight') <- 0.03
edgeData (g, 'lacZ','zraS','weight') <- 0.16
edgeData (g, 'rpoD','lacA','weight') <- 0.03
edgeData (g, 'rpoD','lacI','weight') <- 0.7
edgeData (g, 'rpoD','lacY','weight') <- 0.76
edgeData (g, 'rpoD','lacZ','weight') <- 0.27
edgeData (g, 'rpoD','znuA','weight') <- 0.48
edgeData (g, 'rpoD','hns','weight') <- 0.5
edgeData (g, 'rpoD','crp','weight') <- 0.8
edgeData (g, 'rpoD','ttdA','weight') <- 0.86
edgeData (g, 'rpoD','ttdB','weight') <- 0.46
edgeData (g, 'rpoD','ttdR','weight') <- 0.61
edgeData (g, 'rpoD','ttdT','weight') <- 0.06
edgeData (g, 'rpoD','zraP','weight') <- 0.47
edgeData (g, 'rpoD','zraR','weight') <- 0.76
edgeData (g, 'rpoD','zraS','weight') <- 0.64
edgeData (g, 'rpoD','arsB','weight') <- 0.7
edgeData (g, 'znuA','lacY','weight') <- 0
edgeData (g, 'znuA','lacZ','weight') <- 0.24
edgeData (g, 'znuA','crp','weight') <- 0.01
edgeData (g, 'znuA','ttdA','weight') <- 0.07
edgeData (g, 'znuA','ttdB','weight') <- 0.16
edgeData (g, 'znuA','ttdR','weight') <- 0.21
edgeData (g, 'znuA','zraP','weight') <- 0.46
edgeData (g, 'znuA','zraR','weight') <- 0.04
edgeData (g, 'znuA','zraS','weight') <- 0.14
edgeData (g, 'hns','lacI','weight') <- 0.6
edgeData (g, 'hns','lacY','weight') <- 0.53
edgeData (g, 'hns','lacZ','weight') <- 0.43
edgeData (g, 'hns','rpoD','weight') <- 0.5
edgeData (g, 'hns','znuA','weight') <- 0.87
edgeData (g, 'hns','crp','weight') <- 0.78
edgeData (g, 'hns','ttdA','weight') <- 0.69
edgeData (g, 'hns','ttdB','weight') <- 0.51
edgeData (g, 'hns','ttdR','weight') <- 0.51
edgeData (g, 'hns','ttdT','weight') <- 0.21
edgeData (g, 'hns','zraP','weight') <- 0.54
edgeData (g, 'hns','zraR','weight') <- 0.59
edgeData (g, 'hns','zraS','weight') <- 0.7
edgeData (g, 'hns','arsB','weight') <- 0.9
edgeData (g, 'crp','lacI','weight') <- 0.15
edgeData (g, 'crp','lacY','weight') <- 0.16
edgeData (g, 'crp','lacZ','weight') <- 0.3
edgeData (g, 'crp','znuA','weight') <- 0.24
edgeData (g, 'crp','ttdA','weight') <- 0.36
edgeData (g, 'crp','ttdB','weight') <- 0.31
edgeData (g, 'crp','ttdR','weight') <- 0.39
edgeData (g, 'crp','ttdT','weight') <- 0.03
edgeData (g, 'crp','zraP','weight') <- 0.61
edgeData (g, 'crp','zraR','weight') <- 0.3
edgeData (g, 'crp','zraS','weight') <- 0.46
edgeData (g, 'crp','arsB','weight') <- 0.18
edgeData (g, 'ttdA','lacI','weight') <- 0.02
edgeData (g, 'ttdA','lacY','weight') <- 0.23
edgeData (g, 'ttdA','lacZ','weight') <- 0.38
edgeData (g, 'ttdA','znuA','weight') <- 0.36
edgeData (g, 'ttdA','crp','weight') <- 0.28
edgeData (g, 'ttdA','ttdB','weight') <- 0.56
edgeData (g, 'ttdA','ttdR','weight') <- 0.22
edgeData (g, 'ttdA','zraP','weight') <- 0.37
edgeData (g, 'ttdA','zraR','weight') <- 0.56
edgeData (g, 'ttdA','zraS','weight') <- 0.23
edgeData (g, 'ttdA','arsB','weight') <- 0.32
edgeData (g, 'ttdB','lacY','weight') <- 0.11
edgeData (g, 'ttdB','lacZ','weight') <- 0.11
edgeData (g, 'ttdB','znuA','weight') <- 0.1
edgeData (g, 'ttdB','crp','weight') <- 0
edgeData (g, 'ttdB','ttdA','weight') <- 0.02
edgeData (g, 'ttdB','ttdR','weight') <- 0.23
edgeData (g, 'ttdB','zraP','weight') <- 0.17
edgeData (g, 'ttdB','zraR','weight') <- 0.13
edgeData (g, 'ttdB','zraS','weight') <- 0.16
edgeData (g, 'ttdB','arsB','weight') <- 0.11
edgeData (g, 'ttdR','lacY','weight') <- 0.01
edgeData (g, 'ttdR','lacZ','weight') <- 0.15
edgeData (g, 'ttdR','znuA','weight') <- 0.08
edgeData (g, 'ttdR','crp','weight') <- 0.12
edgeData (g, 'ttdR','ttdA','weight') <- 0.02
edgeData (g, 'ttdR','ttdB','weight') <- 0.17
edgeData (g, 'ttdR','zraP','weight') <- 0.09
edgeData (g, 'ttdR','zraR','weight') <- 0.16
edgeData (g, 'ttdR','zraS','weight') <- 0.22
edgeData (g, 'ttdT','lacA','weight') <- 0.43
edgeData (g, 'ttdT','lacI','weight') <- 0.76
edgeData (g, 'ttdT','lacY','weight') <- 0.59
edgeData (g, 'ttdT','lacZ','weight') <- 0.04
edgeData (g, 'ttdT','rpoD','weight') <- 0.94
edgeData (g, 'ttdT','znuA','weight') <- 0.09
edgeData (g, 'ttdT','hns','weight') <- 0.79
edgeData (g, 'ttdT','crp','weight') <- 0.31
edgeData (g, 'ttdT','ttdA','weight') <- 0.65
edgeData (g, 'ttdT','ttdB','weight') <- 0.17
edgeData (g, 'ttdT','ttdR','weight') <- 0.17
edgeData (g, 'ttdT','zraP','weight') <- 0.11
edgeData (g, 'ttdT','zraR','weight') <- 0.11
edgeData (g, 'ttdT','zraS','weight') <- 0.13
edgeData (g, 'ttdT','arsB','weight') <- 0.63
edgeData (g, 'zraP','lacY','weight') <- 0.02
edgeData (g, 'zraP','lacZ','weight') <- 0.34
edgeData (g, 'zraP','znuA','weight') <- 0.18
edgeData (g, 'zraP','crp','weight') <- 0.01
edgeData (g, 'zraP','ttdA','weight') <- 0.01
edgeData (g, 'zraP','ttdB','weight') <- 0.17
edgeData (g, 'zraP','ttdR','weight') <- 0.24
edgeData (g, 'zraP','zraR','weight') <- 0.04
edgeData (g, 'zraP','zraS','weight') <- 0.06
edgeData (g, 'zraP','arsB','weight') <- 0.03
edgeData (g, 'zraR','lacY','weight') <- 0.38
edgeData (g, 'zraR','lacZ','weight') <- 0.4
edgeData (g, 'zraR','znuA','weight') <- 0.44
edgeData (g, 'zraR','crp','weight') <- 0.27
edgeData (g, 'zraR','ttdA','weight') <- 0.03
edgeData (g, 'zraR','ttdB','weight') <- 0.37
edgeData (g, 'zraR','ttdR','weight') <- 0.36
edgeData (g, 'zraR','zraP','weight') <- 0.37
edgeData (g, 'zraR','zraS','weight') <- 0.4
edgeData (g, 'zraR','arsB','weight') <- 0.19
edgeData (g, 'zraS','lacY','weight') <- 0.02
edgeData (g, 'zraS','lacZ','weight') <- 0.25
edgeData (g, 'zraS','znuA','weight') <- 0.28
edgeData (g, 'zraS','crp','weight') <- 0.08
edgeData (g, 'zraS','ttdA','weight') <- 0.11
edgeData (g, 'zraS','ttdB','weight') <- 0.21
edgeData (g, 'zraS','ttdR','weight') <- 0.18
edgeData (g, 'zraS','zraP','weight') <- 0.31
edgeData (g, 'zraS','zraR','weight') <- 0.3
edgeData (g, 'arsB','lacI','weight') <- 0.35
edgeData (g, 'arsB','lacY','weight') <- 0.59
edgeData (g, 'arsB','lacZ','weight') <- 0.67
edgeData (g, 'arsB','rpoD','weight') <- 0.15
edgeData (g, 'arsB','znuA','weight') <- 0.59
edgeData (g, 'arsB','crp','weight') <- 0.68
edgeData (g, 'arsB','ttdA','weight') <- 0.44
edgeData (g, 'arsB','ttdB','weight') <- 0.55
edgeData (g, 'arsB','ttdR','weight') <- 0.64
edgeData (g, 'arsB','ttdT','weight') <- 0.01
edgeData (g, 'arsB','zraP','weight') <- 0.61
edgeData (g, 'arsB','zraR','weight') <- 0.58
edgeData (g, 'arsB','zraS','weight') <- 0.7


cw@graph <- g
displayGraph (cw)

edges.of.interest = as.character (cy2.edge.names (cw@graph))
setEdgeTargetArrowShapeDirect (cw, edges.of.interest, 'Arrow')
redraw (cw)

#getVisualStyleNames (cw)
setVisualStyle(cw, 'Sample1')

#getLayoutNames(cw)
layoutNetwork (cw, layout.name='degree-circle')
redraw (cw)


